data:
  target_column: loan_status
  positive_class: Default
  train_size: 0.7
  valid_size: 0.15
  test_size: 0.15
  random_state: 42

features:
  categorical:
    - home_ownership        # only existing categorical column
  numerical:
    - loan_amnt
    - annual_inc
    - dti
    - open_acc
    - credit_history_length

model:
  n_estimators: 500
  learning_rate: 0.05
  random_state: 42

evaluation:
  decision_threshold: 0.3
